name: flutter_p2p_example
description: Demonstrates how to use the flutter_p2p plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_p2p:
    path: ../

flutter:
  uses-material-design: true
